### ISSUE TITLE
`sh: mcp-inspector: command not found` after upgrading to v0.10.0

### ISSUE THREAD

**Issue by tadhgboyle** [modelcontextprotocol/inspector#326]
**Describe the bug**
After upgrading to the newest 0.10.0 release, running the command (which worked right before the upgrade) is now failing for me:
```
npx @modelcontextprotocol/inspector
```

**To Reproduce**
1. Upgrade to latest version
2. Run command
3. See issue

**Expected behavior**
I expected it should boot up as per normal

**Logs**
This is all I see now:

<img width="793" alt="Image" src="https://github.com/user-attachments/assets/050cf31c-e1a6-4d83-a385-dcc0524471f5" />

**Comment by shipurjan** [comment]
I have the same problem

Windows 11 24H2

Git bash

0.9.0 works

$ npx @modelcontextprotocol/inspector node
'mcp-inspector' is not recognized as an internal or external command,
operable program or batch file.

$ npx @modelcontextprotocol/inspector@0.9.0 node
Need to install the following packages:
@modelcontextprotocol/inspector@0.9.0
Ok to proceed? (y) y

Starting MCP inspector...
⚙️ Proxy server listening on port 6277
🔍 MCP Inspector is up and running at http://127.0.0.1:6274 🚀

**Comment by localden** [comment]
Same problem on Windows boxes for us. Have to downgrade to 0.9.0.

**Comment by cpang-pallas** [comment]
Same problem in MacOS Sequoia 15.3.2, running `npx @modelcontextprotocol/inspector` in bash results in `sh: mcp-inspector: command not found`

**Comment by cliffhall** [comment]
## What's going on?
* Something seems to have gone wrong in the final npm publishing step. 
* All the code is in the downloadable archive for the release.
* An `npm publish --dry-run` on `main` shows the complete package as what should be published.
* The published package on npm is incomplete.

## Problem is an incomplete package on NPM 
* When I look at the code in the [code tab](https://www.npmjs.com/package/@modelcontextprotocol/inspector?activeTab=code) for the release on NPM, I only see the client folder, package.json, README.

![Image](https://github.com/user-attachments/assets/24abedb5-0567-4e88-8447-5299f7363c49)

## NPM Publish Dry Run contains what _should_ be there
* When I try npm publish dry-run I see all the files that should be published to the 0.10.0 release on NPM.

![Image](https://github.com/user-attachments/assets/2da763f7-ad69-42a4-a7d3-51eb7c624196)

## Source code in Github Release contains what _should_ be there
* When I download the source code zip on [the Github release](https://github.com/modelcontextprotocol/inspector/releases) page I see all the contents

![Image](https://github.com/user-attachments/assets/1177cd40-e1df-4e71-90cd-cd85cf678f64)

**Comment by jpmcb** [comment]
> Something seems to have gone wrong in the final npm publishing step.

How are NPM packages currently being published? Internal Anthropic pipelines? Someone's laptop?

I'd recommend lifting and shifting those processes to the `modelcontextprotocol` org in this repo under a GitHub action for full community visibility and validation https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages#publishing-packages-to-the-npm-registry

A very simple NPM publish action can be triggered on new release:

```yaml
name: Publish Package to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
