### ISSUE TITLE
v0.12.0 is not on NPM - proposal to move releases into GitHub actions

### ISSUE THREAD

**Issue by jpmcb** [modelcontextprotocol/inspector#397]
### Describe the bug

As of 05/12/25, [4 days post release](https://github.com/modelcontextprotocol/inspector/releases/tag/0.12.0), v0.12.0 is not on NPM:

```
❯ npm view @modelcontextprotocol/inspector versions
[
  '0.1.1',  '0.1.2',  '0.1.3',
  '0.1.4',  '0.1.5',  '0.1.6',
  '0.1.7',  '0.2.0',  '0.2.1',
  '0.2.2',  '0.2.3',  '0.2.4',
  '0.2.6',  '0.2.7',  '0.3.0',
  '0.4.0',  '0.4.1',  '0.5.1',
  '0.6.0',  '0.7.0',  '0.8.0',
  '0.8.1',  '0.8.2',  '0.9.0',
  '0.10.0', '0.10.1', '0.10.2',
  '0.11.0'
]
```

### To Reproduce

Go to https://www.npmjs.com/package/@modelcontextprotocol/inspector or run `npm view @modelcontextprotocol/inspector versions` - notice that the latest is still v0.11.0

This also impacts anyone wanting to consume bug fixes / new features off of v0.12 who are using the recommended flow:

```sh
npx @modelcontextprotocol/inspector@latest
```

The following also simply will not work:

```sh
npx @modelcontextprotocol/inspector@0.12.0
npm error code ETARGET
npm error notarget No matching version found for @modelcontextprotocol/inspector@0.12.0.
```

### Expected behavior

I'd expect that when a new GitHub tag is cut, a new NPM version tracks that release _without_ having to involve Anthropic and/or their internal build systems.

This has come up before (where internal Anthropic build systems / publish steps outside this open community broken builds): https://github.com/modelcontextprotocol/inspector/issues/326#issuecomment-2814051008

# Proposal - move build and release workflows into GitHub actions

NPM and GitHub have several mechanisms to securely and dynamically build/release packages. Something like to following is relatively simple and a common pattern in the NPM ecosystem:

```yaml
name: Publish Package to NPM
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages
