### ISSUE TITLE
Unable to connect to MCP server from any popular browser(Chrome, Mozilla, Edge)

### ISSUE THREAD

**Issue by vitaliy-sharandin** [modelcontextprotocol/inspector#499]
Tested every major browser incl. Chrome, Mozilla, Edge to connect to MCP server basic example through inspector UI at `http://127.0.0.1:6274` and `stdio` transport just as user did in #484. The only difference is I don't even get proxy error, no log activity as well.
Only `DuckDuckGo` and `VSCode Simple Browser` browsers were able to connect to my server.
[One user at Stack Overflow](https://stackoverflow.com/questions/79582846/the-python-mcp-server-with-stdio-transport-throws-an-error-sse-connection-not/79659309#79659309) was also having same troubles.

**Comment by olaservo** [comment]
Not seeing other reports of this being a bug and I am unable to repro, but please comment if you still need help debugging this scenario.

**Comment by jokob-sk** [comment]
Confirm, still an issue - took me an hour to get it working - got it working with this docker-compose - I'd suggest to add it to the docs for IPv4 setups

```yaml
name: mcp-inspector
services:
    mcp-inspector:
        image: ghcr.io/modelcontextprotocol/inspector:latest
        network_mode: bridge
        ports:
            - 6274:6274
            - 6277:6277
        environment:
            - DANGEROUSLY_OMIT_AUTH=true
            - HOST=0.0.0.0
        command: ["npm", "start", "--", "--host", "0.0.0.0"]
```
